import Head from 'next/head'
import CustomInput from '../components/CustomInput'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Next Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>this is a resuable input component</h1>
      <CustomInput type="number" placeHolder="123"/>
    </div>
     
  )
}
